### ISSUE TITLE
Numpy comments convention

### ISSUE THREAD

**Issue by muzikr** [muzikr/Shapleypy#33]
Currently I have added some basic comments so the library would be at least little documented. I should improve them and use numpy convention for pydocstyle. I can set the ruff to check the convention by adding ```"D"``` to ```[tool.ruff.ling.select]``` and by adding:

```toml
[tool.ruff.lint.pydocstyle]
convention = "numpy"
```

Numpy convention style guide:
- https://numpydoc.readthedocs.io/en/latest/format.html
